// Code generated by cmd/bootstrap; DO NOT EDIT.
package pattern_cli

import (
	"fmt"
	"image"
	"strconv"
	"github.com/arran4/go-pattern"
	"github.com/arran4/go-pattern/dsl"
)

func init() {
	RegisterGeneratedCommands = func(fm dsl.FuncMap) {
		fm["screentone"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["crosshatch"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		// Warning: Constructor NewCrackedMud not found for crackedmud
		fm["scales"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		// Warning: Constructor NewMolecules not found for molecules
		fm["tile"] = func(args []string, input image.Image) (image.Image, error) {
			// Unsupported arg type: image.Rectangle
			return nil, fmt.Errorf("command tile has unsupported arguments")
			return nil, fmt.Errorf("not implemented yet")
		}
		// Warning: Constructor NewCells not found for cells
		// Warning: Constructor NewStones not found for stones
		fm["worleynoise"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["null"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		// Warning: Constructor NewIslands not found for islands
		fm["polka"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["voronoi"] = func(args []string, input image.Image) (image.Image, error) {
			// Unsupported arg type: []image.Point
			return nil, fmt.Errorf("command voronoi has unsupported arguments")
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["shojo"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		// Warning: Constructor NewShojo_blue not found for shojo_blue
		// Warning: Constructor NewShojo_pink not found for shojo_pink
		fm["checker"] = func(args []string, input image.Image) (image.Image, error) {
			if len(args) <= 0 {
				return nil, fmt.Errorf("argument 1 (color) missing")
			}
			c0, err := parseColor(args[0])
			if err != nil {
				return nil, err
			}
			if len(args) <= 1 {
				return nil, fmt.Errorf("argument 2 (color) missing")
			}
			c1, err := parseColor(args[1])
			if err != nil {
				return nil, err
			}
			return pattern.NewChecker(c0, c1), nil
		}
		fm["grid"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		// Warning: Constructor NewGridUnbounded not found for gridunbounded
		fm["padding"] = func(args []string, input image.Image) (image.Image, error) {
			if input == nil {
				return nil, fmt.Errorf("input image required")
			}
			return pattern.NewPadding(input), nil
		}
		fm["horizontalline"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["verticalline"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["noise"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["rect"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["gopher"] = func(args []string, input image.Image) (image.Image, error) {
			return pattern.NewGopher(), nil
		}
		// Warning: Constructor NewMathsMandelbrot not found for mathsmandelbrot
		// Warning: Constructor NewBooleanAnd not found for booleanand
		// Warning: Constructor NewBooleanOr not found for booleanor
		// Warning: Constructor NewMathsJulia not found for mathsjulia
		// Warning: Constructor NewBooleanXor not found for booleanxor
		// Warning: Constructor NewMathsSine not found for mathssine
		// Warning: Constructor NewBooleanNot not found for booleannot
		// Warning: Constructor NewMathsWaves not found for mathswaves
		fm["heatmap"] = func(args []string, input image.Image) (image.Image, error) {
			// Unsupported arg type: HeatmapFunc
			return nil, fmt.Errorf("command heatmap has unsupported arguments")
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["circle"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["colormap"] = func(args []string, input image.Image) (image.Image, error) {
			if input == nil {
				return nil, fmt.Errorf("input image required")
			}
			return pattern.NewColorMap(input), nil
		}
		fm["fibonacci"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["speedlines"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["quantize"] = func(args []string, input image.Image) (image.Image, error) {
			if input == nil {
				return nil, fmt.Errorf("input image required")
			}
			if len(args) <= 0 {
				return nil, fmt.Errorf("argument 1 (int) missing")
			}
			i0, err := strconv.Atoi(args[0])
			if err != nil {
				return nil, fmt.Errorf("invalid int argument: %%w", err)
			}
			return pattern.NewQuantize(input, i0), nil
		}
		fm["lineargradient"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		// Warning: Constructor NewXorGrid not found for xorgrid
		fm["simplezoom"] = func(args []string, input image.Image) (image.Image, error) {
			if input == nil {
				return nil, fmt.Errorf("input image required")
			}
			if len(args) <= 0 {
				return nil, fmt.Errorf("argument 1 (int) missing")
			}
			i0, err := strconv.Atoi(args[0])
			if err != nil {
				return nil, fmt.Errorf("invalid int argument: %%w", err)
			}
			return pattern.NewSimpleZoom(input, i0), nil
		}
		fm["transposed"] = func(args []string, input image.Image) (image.Image, error) {
			if input == nil {
				return nil, fmt.Errorf("input image required")
			}
			if len(args) <= 0 {
				return nil, fmt.Errorf("argument 1 (int) missing")
			}
			i0, err := strconv.Atoi(args[0])
			if err != nil {
				return nil, fmt.Errorf("invalid int argument: %%w", err)
			}
			if len(args) <= 1 {
				return nil, fmt.Errorf("argument 2 (int) missing")
			}
			i1, err := strconv.Atoi(args[1])
			if err != nil {
				return nil, fmt.Errorf("invalid int argument: %%w", err)
			}
			return pattern.NewTransposed(input, i0, i1), nil
		}
		fm["bayer2x2dither"] = func(args []string, input image.Image) (image.Image, error) {
			// Unsupported arg type: color.Palette
			return nil, fmt.Errorf("command bayer2x2dither has unsupported arguments")
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["radialgradient"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["modulostripe"] = func(args []string, input image.Image) (image.Image, error) {
			// Unsupported arg type: []color.Color
			return nil, fmt.Errorf("command modulostripe has unsupported arguments")
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["concentricrings"] = func(args []string, input image.Image) (image.Image, error) {
			// Unsupported arg type: []color.Color
			return nil, fmt.Errorf("command concentricrings has unsupported arguments")
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["mirror"] = func(args []string, input image.Image) (image.Image, error) {
			// Unsupported arg type: bool
			return nil, fmt.Errorf("command mirror has unsupported arguments")
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["conicgradient"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["plasma"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["rotate"] = func(args []string, input image.Image) (image.Image, error) {
			if input == nil {
				return nil, fmt.Errorf("input image required")
			}
			if len(args) <= 0 {
				return nil, fmt.Errorf("argument 1 (int) missing")
			}
			i0, err := strconv.Atoi(args[0])
			if err != nil {
				return nil, fmt.Errorf("invalid int argument: %%w", err)
			}
			return pattern.NewRotate(input, i0), nil
		}
		fm["bayerdither"] = func(args []string, input image.Image) (image.Image, error) {
			if input == nil {
				return nil, fmt.Errorf("input image required")
			}
			if len(args) <= 0 {
				return nil, fmt.Errorf("argument 1 (int) missing")
			}
			i0, err := strconv.Atoi(args[0])
			if err != nil {
				return nil, fmt.Errorf("invalid int argument: %%w", err)
			}
			return pattern.NewBayerDither(input, i0), nil
		}
		fm["bluenoise"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		// Warning: Constructor NewGradientQuantization not found for gradientquantization
		fm["bitwiseand"] = func(args []string, input image.Image) (image.Image, error) {
			// Unsupported arg type: []image.Image
			return nil, fmt.Errorf("command bitwiseand has unsupported arguments")
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["sierpinskitriangle"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["vhs"] = func(args []string, input image.Image) (image.Image, error) {
			if input == nil {
				return nil, fmt.Errorf("input image required")
			}
			return pattern.NewVHS(input), nil
		}
		fm["sierpinskicarpet"] = func(args []string, input image.Image) (image.Image, error) {
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["edgedetect"] = func(args []string, input image.Image) (image.Image, error) {
			if input == nil {
				return nil, fmt.Errorf("input image required")
			}
			return pattern.NewEdgeDetect(input), nil
		}
		fm["errordiffusion"] = func(args []string, input image.Image) (image.Image, error) {
			// Unsupported arg type: DiffusionKernel
			return nil, fmt.Errorf("command errordiffusion has unsupported arguments")
			return nil, fmt.Errorf("not implemented yet")
		}
		fm["ordereddither"] = func(args []string, input image.Image) (image.Image, error) {
			// Unsupported arg type: []float64
			return nil, fmt.Errorf("command ordereddither has unsupported arguments")
			return nil, fmt.Errorf("not implemented yet")
		}
	}
}

var RegisterGeneratedCommands func(dsl.FuncMap)
